apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 289349975759.dkr.ecr.us-east-2.amazonaws.com/helloworldservlet:latest
          ports:
            - containerPort: 8080
