#EKS build and deploy
name: Build and Push Java App to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: helloworldservlet
  IMAGE_TAG: latest
  EKS_CLUSTER_NAME: my-cluster
  EKS_NAMESPACE: my-namespace
  EKS_DEPLOYMENT_NAME: my-deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Java application
        run: mvn -B package --file pom.xml
        
      - name: Copy the WAR file to the Docker build context
        run: cp target/*.war docker/helloworld.war            

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./docker
          # Set the AWS account ID and ECR repository URI
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
          # Tag the Docker image with the ECR repository URI
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker images
          #Display Account ID and ECR URL
          echo "Display Account ID and ECR_URI"
          echo $AWS_ACCOUNT_ID
          echo $ECR_URI
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 289349975759.dkr.ecr.us-east-2.amazonaws.com/helloworldservlet
      - name: Install and configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Docker image to Amazon EKS
        env:
          ECR_REGISTRY: $(echo $(cat ecr-registry.json) | base64 -d | jq -r '.registry')
          ECR_USERNAME: $(echo $(cat ecr-registry.json) | base64 -d | jq -r '.username')
          ECR_PASSWORD: $(echo $(cat ecr-registry.json) | base64 -d | jq -r '.password')
        run: |
          kubectl set image deployment/${{ env.EKS_DEPLOYMENT_NAME }} ${{ env.EKS_DEPLOYMENT_NAME }}=${ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} --namespace=${{ env.EKS_NAMESPACE }}
        shell: bash        
          
